version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/hospital
  postgres:
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: director
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: hospital
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: